RomeoConnection/Models/PostComment.cs
using System.ComponentModel.DataAnnotations;

namespace RomeoConnection.Models
{
    public class PostComment
    {
        public int Id { get; set; }

        [Required]
        [StringLength(3000)]
        public string CommentText { get; set; }

        public virtual ApplicationUser CommentBy { get; set; }

        [Required]
        public string CommentById { get; set; }

        public UserPost UserPost { get; set; }

        public int UserPostId { get; set; }

        public string CommentStatus { get; set; }



    }
}

RomeoConnection/Controllers/PostCommentsController.cs
using Microsoft.AspNet.Identity;
using RomeoConnection.Models;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;

namespace RomeoConnection.Controllers
{
    public class PostCommentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PostCommentsController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpPost]
        public ActionResult CreatePostComment(PostComment createdComment)
        {


            ModelState.Remove("CommentById");

            var userId = User.Identity.GetUserId();
            var currentUser = _context.Users.Single(u => u.Id == userId);

            var errors = ModelState.Values.SelectMany(v => v.Errors);
            Debug.WriteLine(errors);

            var newComment = new PostComment
            {
                CommentText = createdComment.CommentText,
                CommentBy = currentUser,
                CommentById = userId,
                UserPostId = createdComment.UserPostId,
                CommentStatus = "pending"
            };
            try
            {
                _context.PostComments.Add(newComment);
                _context.SaveChanges();
                Debug.WriteLine("Felicitari Jordi");
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        Debug.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }
            }

            var selectedPost = _context.UserPostsList.Where(u => u.Id == createdComment.UserPostId);

            selectedPost.ToList().FirstOrDefault().Comments.Add(newComment);
            _context.SaveChanges();


            return RedirectToAction("Index", "Home");
        }
    }
}

RomeoConnection/Views/PostComments/_AddComment.cshtml
@model RomeoConnection.Models.PostComment



    @using (Html.BeginForm("CreatePostComment", "PostComments", FormMethod.Post,
        new {@class = "form-horizontal",}))
    {
        <div class="form-group" id="add-comment">
            <div class="col-md-10">
                @Html.TextAreaFor(comment => comment.CommentText, new { style = "width: 50%; max-width: none !important;", placeholder = "Say something" })
                @Html.ValidationMessage("CustomMessage")
                <button class="btn btn-primary">Post</button>
            </div>
        </div>
        @Html.HiddenFor(model => model.UserPostId, new { Value= Convert.ToInt32(@ViewData["UserPostId"]) })
@*         <p>@ViewData["UserPostId"]</p> *@
    }