RomeoConnection/Models/UserPost.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace RomeoConnection.Models
{
    public class UserPost
    {
        public int Id { get; set; }

        public virtual ApplicationUser ApplicationUser { get; set; }

        [Required]
        [StringLength(254)]
        public string ApplicationUserId { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [Required]
        [StringLength(3000)]
        public string Description { get; set; }

        public byte[] PostPicture { get; set; }

        public bool IsDeleted { get; set; }

        [NotMapped]
        public HttpPostedFileBase UserPostPicture { get; set; }

        public virtual List<PostComment> Comments { get; set; }
    }
}

RomeoConnection/Controllers/PendingPostCommentsController.cs
using Microsoft.AspNet.Identity;
using RomeoConnection.Dtos;
using RomeoConnection.Models;
using System;
using System.Linq;
using System.Web.Http;

namespace RomeoConnection.Controllers
{
    public class PendingPostCommentsController : ApiController
    {
        private readonly ApplicationDbContext _context;

        public PendingPostCommentsController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpPost]
        public IHttpActionResult PendingPostComment(PendingPostComment dto)
        {
            var userId = User.Identity.GetUserId();
            var postId = Int32.Parse(dto.postComment);
            var postComment = _context.PostComments.Where(p => p.Id == postId).FirstOrDefault();

            if (postComment.CommentStatus != "declined")
            {
                if (postComment.CommentStatus == "approved")
                {
                    return BadRequest("Comment already approved");
                }
                else
                {
                    postComment.CommentStatus = "approved";
                    _context.SaveChanges();
                }
            }
            else
            {
                return BadRequest("Comment DECLINED");
            }

            return Ok();

        }

        //De facut ca mai sus
        //        public IHttpActionResult DeclinePostComment(PostComment model)
        //        {
        //            var userId = User.Identity.GetUserId();
        //            model.CommentStatus = "declined";
        //            _context.SaveChanges();
        //
        //            return Ok();
        //        }
    }
}

RomeoConnection/Controllers/UserPostController.cs
using Microsoft.AspNet.Identity;
using RomeoConnection.Models;
using System;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;

namespace RomeoConnection.Controllers
{
    public class UserPostController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserPostController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: UserPost
        [Authorize]
        public ActionResult CreatePost()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePost(UserPost createdPost)
        {
            ModelState.Remove("ApplicationUserId");
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            Debug.WriteLine(errors);

            if (!ModelState.IsValid)
            {
                Debug.WriteLine(!ModelState.IsValid);
                return View("CreatePost", createdPost);
            }

            var userId = User.Identity.GetUserId();
            var currentUser = _context.Users.Single(u => u.Id == userId);

            byte[] data = null;
            try
            {
                data = new byte[createdPost.UserPostPicture.ContentLength];
                createdPost.UserPostPicture.InputStream.Read(data, 0, createdPost.UserPostPicture.ContentLength);
            }
            catch (Exception exception)
            {
                Debug.WriteLine("Problema este : {0} ", exception.Message);
            }
            var newPost = new UserPost()
            {

                ApplicationUser = currentUser,
                ApplicationUserId = currentUser.Id,
                Title = createdPost.Title,
                Description = createdPost.Description,
                PostPicture = data,
                //                Users = new List<ApplicationUser>() { currentUser }
            };

            try
            {
                _context.UserPostsList.Add(newPost);
                _context.SaveChanges();
                Debug.WriteLine("Felicitari Jordi");
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        Debug.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }
            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult PendingPostComments()
        {
            var userId = User.Identity.GetUserId();
            //            var currentUser = _context.Users.Single(u => u.Id == userId);
            var myPosts = _context.UserPostsList.Where(p => p.ApplicationUserId == userId && p.Comments.Any()).ToList();
            //            var myPendingPosts = myPosts.Where(p => p.Comments.Where(c => c.CommentStatus == "pending"));
            return View("PendingPostComments", myPosts);
        }

        public ActionResult ApprovePostComment(PostComment model)
        {
            var userId = User.Identity.GetUserId();
            model.CommentStatus = "approved";
            _context.SaveChanges();

            return new EmptyResult();

        }

        public ActionResult DeclinePostComment(PostComment model)
        {
            var userId = User.Identity.GetUserId();
            model.CommentStatus = "declined";
            _context.SaveChanges();

            return new EmptyResult();
        }

    }
}

RomeoConnection/Views/UserPost/CreatePost.cshtml
@model  RomeoConnection.Models.UserPost
@{
    ViewBag.Title = "CreatePost";
}

<h2>Say something...</h2>
@using (Html.BeginForm("CreatePost", "UserPost", FormMethod.Post, 
    new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(post => post.Title)
        @Html.TextBoxFor(post => post.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(post => post.Title)
    </div>
    <div class="form-group">
        @Html.LabelFor(post => post.Description)
        @Html.TextBoxFor(post => post.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(post => post.Description)
    </div>
    <div class="form-group">
        @Html.LabelFor(post => post.PostPicture, "Add a picture ", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(post => post.UserPostPicture, new { type = "file" })
            @Html.ValidationMessage("CustomMessage")
        </div>
    </div>
    <br/>
    <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Post" />
    </div>


}

RomeoConnection/Views/UserPost/PendingPostComments.cshtml
@using Newtonsoft.Json.Linq
@model List<RomeoConnection.Models.UserPost>
    
<h2>Pending Comments for my posts</h2>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>CommentText</th>
        <th>CommentBy</th>
        <th>Picture</th>
        <th>Comments</th>


    </tr>
    </thead>
    <tbody>
    @if(Model != null)
    {
        foreach (var post in Model)
        {
            var base64 = "";
            if (post.PostPicture != null && post.PostPicture.Length > 0)
            {
                var aux = post.PostPicture;
                base64 = Convert.ToBase64String(aux);
            }
            <tr>
                <td>@post.Title</td>

                <td>@post.Description</td>
                <td>
                    <img alt="" src='@(string.Format("data:image/jpeg;base64,{0}", base64))'
                         width="200px" , height="auto"/>
                </td>
                <td>
                    @{

                        foreach (var comment in post.Comments)
                         {
                             if (comment.CommentStatus == "pending")
                             {
                                 <div style="margin: 20px; background-color: red;">
                                     <p>@comment.CommentBy.FirstName @comment.CommentBy.LastName </p>
                                     <p>@comment.CommentText</p>
                                     <button data-post-comment="@comment.Id" class="btn btn-primary js-comment-approve">Approve</button>
                                     @* <button class="btn btn-primary">Decline @Html.Action("DeclinePostComment", "UserPost", new {comment})</button> *@
                                 </div>
                             }
                         }
                    }
                </td>
                @*             <td> *@
                @*                 @{ *@
                @*                     if (Model.ShowActions) *@
                @*                     { *@
                @*                         <button data-user-id="@user.DisplayId" class="btn btn-primary js-toggle-follow">Add Friend</button> *@
                @*                         <p class="number">Aveti 8 prieteni comuni</p> *@
                @* *@
                @*                     } *@
                @*                     else *@
                @*                     { *@
                @*                         <span>You must register before sending friend requests</span> *@
                @*                     } *@
                @* } *@

                @* </td> *@

            </tr>
        }
    }
    </tbody>
</table>

@section scripts{
    <script>

        $(document).ready(function() {

            $(".js-comment-approve").click(function(e) {
                var button = $(e.target);
                $.post("../api/PendingPostComments", { postComment: button.attr("data-post-comment") })

                    .done(function() {
                        button
                            .removeClass("btn-primary")
                            .addClass("btn-member")
                            .text("Already APPROVED");
                    })
                    .fail(function() {
                        alert("Oops! Something failed! Try again");
                    });
            });
        });
    </script>
}