RomeoConnection/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RomeoConnection.Models
{
    public class Group
    {
        public int Id { get; set; }

        [Required]
        [StringLength(254)]
        public String Title { get; set; }


        [Required]
        [StringLength(3000)]
        public String Description { get; set; }

        public int NumberOfUsers { get; set; }

        public List<ApplicationUser> Users { get; set; }

        [Required]
        public string CreatedById { get; set; }
        public ApplicationUser CreatedBy { get; set; }

        //DE INLOCUIT APPLICATIONUSER CU USER

        public int NrUsers { get; set; }
    }
}

RomeoConnection/ViewModels/GroupDetailsViewModel.cs
using RomeoConnection.Models;
using System.Collections.Generic;

namespace RomeoConnection.ViewModels
{
    public class GroupDetailsViewModel
    {
        public Group Group { get; set; }

        public List<GroupPost> GroupPosts { get; set; }

        public GroupPost GroupPost { get; set; }
    }
}

RomeoConnection/ViewModels/GroupViewModel.cs
using System.Collections.Generic;
using RomeoConnection.Models;

namespace RomeoConnection.ViewModels
{
    public class GroupViewModel
    {
        public IEnumerable<Group> Groups { get; set; }
        public bool ShowActions { get; set; }
    }
}

RomeoConnection/Controllers/GroupPostsController.cs
using Microsoft.AspNet.Identity;
using RomeoConnection.Models;
using RomeoConnection.ViewModels;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;

namespace RomeoConnection.Controllers
{
    public class GroupPostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GroupPostsController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult CreateGroupPost(GroupDetailsViewModel model)
        {
            var userId = User.Identity.GetUserId();
            var currentUser = _context.Users.Single(u => u.Id == userId);

            var groupPost = new GroupPost
            {
                GroupId = model.Group.Id,
                ApplicationUser = currentUser,
                ApplicationUserId = userId,
                Title = model.GroupPost.Title,
                Description = model.GroupPost.Description
            };
            try
            {
                _context.GroupPosts.Add(groupPost);
                _context.SaveChanges();
                Debug.WriteLine("Felicitari Jordi");
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        Debug.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }
            }

            return RedirectToAction("GroupDetails", "Groups", new { id = groupPost.GroupId });
        }
    }
}

RomeoConnection/Controllers/GroupsController.cs
using Microsoft.AspNet.Identity;
using RomeoConnection.Models;
using RomeoConnection.ViewModels;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;

namespace RomeoConnection.Controllers
{
    public class GroupsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GroupsController()
        {
            _context = new ApplicationDbContext();
        }


        [Authorize]
        public ActionResult MyGroups()
        {
            var userId = User.Identity.GetUserId();
            var groups = _context.GroupMembers
                .Where(m => m.GroupMemberUserId == userId)
                .Select(g => g.Group)
                .ToList();
            //Daca primesti null pointer exception trebuie sa adaugi Include(ceva => ceva.altceva),
            // unde ceva si altceva sunt proprietatile din alte tabele ( de exemplu pentru calendar)
            var viewModel = new GroupViewModel()
            {
                Groups = groups,
                ShowActions = User.Identity.IsAuthenticated
            };
            return View(viewModel);

        }

        // GET: Groups
        public ActionResult Index()
        {
            var groups = GetGroups();

            var viewModel = new GroupViewModel
            {
                Groups = groups,
                ShowActions = User.Identity.IsAuthenticated,
            };

            return View(viewModel);
        }

        [Authorize(Roles = "Admin,RegularUser")]
        public ActionResult CreateGroup()
        {

            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateGroup(Group createdGroup)
        {
            ModelState.Remove("CreatedById");
            //            var errors = ModelState.Values.SelectMany(v => v.Errors);
            //            Debug.WriteLine(errors);
            if (!ModelState.IsValid)
            {
                //                Debug.WriteLine(!ModelState.IsValid);
                return View("CreateGroup", createdGroup);
            }
            var userId = User.Identity.GetUserId();
            var currentUser = _context.Users.Single(u => u.Id == userId);
            var newGroup = new Group
            {
                CreatedBy = currentUser,
                CreatedById = currentUser.Id,
                Title = createdGroup.Title,
                Description = createdGroup.Description,
                NumberOfUsers = 1,
                Users = new List<ApplicationUser>() { currentUser }
            };

            try
            {
                _context.GroupList.Add(newGroup);
                _context.SaveChanges();
                Debug.WriteLine("Felicitari Jordi");
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        Debug.WriteLine("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }
            }

            return RedirectToAction("Index", "Groups");
        }

        private IEnumerable<Group> GetGroups()
        {

            return _context.GroupList;
        }


        public ActionResult GroupDetails(int id)
        {
            var group = _context.GroupList.Where(g => g.Id == id).First();
            var userId = User.Identity.GetUserId();
            var myGroups = _context.GroupMembers
                .Where(m => m.GroupMemberUserId == userId)
                .Select(g => g.Group)
                .ToList();

            var groupPosts = _context.GroupPosts.Where(g => g.GroupId == id).ToList();

            var groupDetailsViewModel = new GroupDetailsViewModel()
            {
                Group = group,
                GroupPosts = groupPosts,
            };

            if (group != null && myGroups.Contains(group))
                return View(groupDetailsViewModel);

            return RedirectToAction("Index", "Groups");
        }
    }
}

RomeoConnection/Views/Groups/CreateGroup.cshtml
@using Newtonsoft.Json.Linq
@model RomeoConnection.Models.Group
@{
    ViewBag.Title = "CreateGroup";
}

<h2>Create a new group !</h2>
<br/>

@using (Html.BeginForm("CreateGroup", "Groups"))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(group => group.Title)
        @Html.TextBoxFor(group => group.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(group => group.Title)
    </div>
    <div class="form-group">
        @Html.LabelFor(group => group.Description)
        @Html.TextBoxFor(group => group.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(group => group.Description)
    </div>
    <button type="submit" value="save" class="btn btn-primary">Save</button>
}

@section scripts {
   @Scripts.Render("~/bundles/jqueryval")
}

RomeoConnection/Views/Groups/GroupDetails.cshtml
@model RomeoConnection.ViewModels.GroupDetailsViewModel
@{
    ViewBag.Title = "MyGroups";
}

<h2>@Model.Group.Title</h2>

<h2>Say something...</h2>
@using (Html.BeginForm("CreateGroupPost", "GroupPosts", FormMethod.Post, 
    new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(g => g.GroupPost.Title)
        @Html.TextBoxFor(g => g.GroupPost.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(g => g.GroupPost.Title)
    </div>
    <div class="form-group">
        @Html.LabelFor(g => g.GroupPost.Description)
        @Html.TextBoxFor(g => g.GroupPost.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(g => g.GroupPost.Description)
    </div>
    <div class="form-group">
        @Html.LabelFor(g => g.GroupPost.PostPicture, "Add a picture ", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(g => g.GroupPost.GroupPostPicture, new { type = "file" })
            @Html.ValidationMessage("CustomMessage")
        </div>
        @Html.HiddenFor(g => g.Group.Id, new { Value= Model.Group.Id })
    </div>
    <br/>
    <div class="form-group">
        @* <input type="submit" class="btn btn-primary" value="Post" />      new { id = Model.Group.Id })*@
        <button type="submit" class="btn btn-primary">Add a post</button>
    </div>


}


<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>Titlu</th>
        <th>Descriere</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>@Model.Group.Title</td>
        <td>@Model.Group.Description</td>
        <p>@Model.Group.Id</p>
    </tr>
    </tbody>
</table>

@{
    foreach (var groupPost in Model.GroupPosts)
    {
        <div>
            <p>Author : @groupPost.ApplicationUser.FirstName  @groupPost.ApplicationUser.LastName</p>
            <p style="font-weight: bold; font-size: 18px;">@groupPost.Title</p>
            <p>Message : @groupPost.Description</p>
        </div>
    }
}

RomeoConnection/Views/Groups/Index.cshtml
@using System.Web.Mvc.Html
@using System.Web.UI.WebControls
@model RomeoConnection.ViewModels.GroupViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Join a group !</h2>


    @foreach (var group in Model.Groups )
    {

        <div class="card-example">
            <div class="card card-inverse">
                <div class="card-block">
                    <h3 class="card-title">
                        @group.Title
                    </h3>
                    <p class="card-text">
                         @group.Description
                    </p>
                </div>
                @{
                    if (Model.ShowActions)
                    {
                        <button data-group-id="@group.Id" class="btn btn-primary js-toggle-membership">Join</button>
                        <p class="number">33 de utilizatori s-au inscris deja</p>
                        <button class="btn btn-primary"><a href="@Url.Action("GroupDetails", "Groups", new { id = group.Id })">View group</a></button>
                            }
                    else
                    {
                        <span>You must register before joining a group</span>
                        }
                }

            </div>
        </div>

                  
@* //                </li> *@

    }
@* </ul> *@


@section scripts{
    <script>

        $(document).ready(function() {

                $(".js-toggle-membership").click(function(e) {
                    var button = $(e.target);
                    $.post("api/GroupMembers", { groupId : button.attr("data-group-id") })

            .done(function() {
                            button
                                .removeClass("btn-primary")
                                .addClass("btn-member")
                                .text("Joined");
                        })
            .fail(function() {
                alert("Oops! Something failed! Try again");
            });
    });
    });
    </script>
}

RomeoConnection/Views/Groups/MyGroups.cshtml
@model RomeoConnection.ViewModels.GroupViewModel
@{
    ViewBag.Title = "MyGroups";
}

<h2>My Groups : </h2>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Titlu</th>
            <th>Descriere</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var group in Model.Groups)
        {
            <tr>
                <td>@group.Title</td>
                <td>@group.Description</td>
                <td>
                    @{
                        if (Model.ShowActions)
                        {
                            <button data-group-id="@group.Id" class="btn btn-primary js-toggle-membership">Join</button>
                        }
                        else
                        {
                            <span>You must register before joining a group</span>
                        }
                    }
                </td>

            </tr>
        }
    </tbody>
</table>